site_name: Introduction to R and RStudio
site_url: https://finnsdottir.github.io/intro_r_fall2025
theme:
  name: material
  palette:
    primary: deep purple
  features:
  - navigation.sections
  - navigation.top
  - content.code.copy

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys

nav:
  - Introduction: index.md
  - Land Acknowledgement: land_acknowledgement.markdown
  - Getting started:
    - R & RStudio: rstudio.md
    - Basic Syntax: basics.md
    - Creating a Project: getting_started.md 
  - Working with Data:
    - Inspecting Data: inspecting.md
    - Wrangling Data: analysing.md 
    - Visualizing Data: visualizing.md

extra_css:
  - stylesheets/extra.css

extra:
  social:
    -icon: ./content/by-nc.png
     link: https://creativecommons.org/licenses/by-nc/4.0/

